Repository app-outlet/app-outlet, pull requests merged in 2019-09, with the labels that each got.

#9 changing icons
  README.md
  src/assets/icon.png
Labels: enhancement

#18 fix: validate query before do search
  src/app/presentation/main/main.presenter.ts
Labels: bug, frontend

#20 Loading on Search result
  src/app/presentation/main/main.presenter.ts
  src/app/presentation/search-result/search-result.component.html
  src/app/presentation/search-result/search-result.component.ts
  src/app/presentation/search-result/search-result.presenter.ts
  src/app/shared/components/section/section.component.ts
  src/assets/i18n/en.json
Labels: enhancement, frontend

#21 go to home on icon click
  src/app/presentation/main/main.component.html
Labels: enhancement, frontend

#23 notify view
  src/app/core/repository/app/app.repository.ts
  src/app/core/services/app/app.service.ts
  src/app/shared/components/app-card/app-card.component.ts
Labels: enhancement, feature

#26 Melhorias no readme
  LICENSE
  LICENSE.MD
  README.md
  screenshot.png
Labels: documentation

#29 Bugfix/select browser language
  src/app/app.component.ts
Labels: enhancement
